name: 'Deploy "Soul Pawnshop"'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: deploy
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@app.mistait.com:22/gamecomparsion-sp'
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
